# Generated by Django 5.2.9 on 2026-01-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_businessprofile_expected_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='timeline',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
