# Generated by Django 5.2.9 on 2026-01-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_businessprofile_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='investment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='timeline',
            field=models.CharField(max_length=100),
        ),
    ]
