# Generated by Django 5.2.9 on 2026-01-03 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='timeline',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 3)),
            preserve_default=False,
        ),
    ]
