# Generated by Django 5.2.9 on 2026-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_businessprofile_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='expected_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
