# Generated by Django 5.2.9 on 2026-01-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
