# Generated by Django 5.2.9 on 2026-01-08 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='target',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
