# Generated by Django 5.2.9 on 2026-01-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='actual_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
