# Generated by Django 5.2.9 on 2026-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_contactmessage_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_reply_sender',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_reply_target',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_reply_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
